version: '3.9'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      -  ${USER_HOME}/jenkins:/var/jenkins_home
      -  /var/run/docker.sock:/var/run/docker.sock
      